name: modtran
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - python=3.7.*
  - click
  - pandas
  - scipy
  - matplotlib
  - jupyter
  - jupytext
  - attrs
  - toml
  - pip
  - pip:
    - git+https://github.com/executablebooks/MyST-NB.git



